language: python
services:
 - mongodb
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - REPO=`pwd`
 - echo $REPO
 - pwd
 - "locale-gen en_US.UTF-8 && export LANG=en_US.UTF-8 && LC_ALL=en_US.UTF-8"
 - "sudo add-apt-repository -y ppa:ondrej/php"
 - "sudo apt-get -qq update"
 - "sudo apt-get -qq install python-dev gfortran"
 - "sudo apt-get install -y -q libxml2"
 - "sudo apt-get install dnsutils"
 - "sudo service mongodb start"
# Dependencies for the php sandbox
 - "sudo apt-get -qq install php7.0 php7.0-dev"
# Install hpfeeds
 - cd /tmp
 - git clone git://github.com/rep/hpfeeds.git hpfeeds
 - cd hpfeeds
 - python setup.py install
# Install Better Function Replacer (BFR)
 - cd /tmp
 - git clone git://github.com/mushorg/BFR.git
 - cd BFR
 - phpize7.0
 - ./configure --enable-bfr
 - make
 - sudo make install
# TODO: Extract path from output
 - sudo bash -c 'echo "zend_extension = "$(find /usr -name bfr.so) >> /etc/php/7.0/cli/php.ini'
 - php7.0 --version
 - cd $REPO
 - cd glastopf
 - cd sandbox
 - sudo make
 - pwd
# install pylibinjection
 - cd /tmp
 - pip install cython
 - git clone --recursive https://github.com/mushorg/pylibinjection.git
 - cd pylibinjection
 - python setup.py install
install:
 - export PYTHONIOENCODING=UTF8 # just in case
 - pwd
 - cd $REPO
 - pip install -r requirements.txt --use-mirrors
# command to run tests
script: 
 - echo $REPO
 - pwd
 - nosetests
notifications:
 irc:
  - "irc.freenode.org#glastopf"
